### ISSUE TITLE
How to connect

### ISSUE THREAD

**Issue by jdschuitemaker** [Nihilissimis/Remeha2MQTT#1]
I have a Remeha Calenta 40C. I would like to use your code but have no idea how to connect the ESP8266 to the Calenta. Do you happen to know where I can find the pins on the C40? I haven't found anything in the manual too.

**Comment by Nihilissimis** [comment]
The 4P4C (RJ9/10 style) connector can be found after removing the protective cover on the top right of the plastic enclosure that holds the electronics. 
The Installer's Manual (cannot share, but can be found online: "Installatie- en servicehandleiding", 104 pages) has more detailed technical drawings.

**Comment by jdschuitemaker** [comment]
Thank you very much! Going to look into this soon!

**Comment by jdschuitemaker** [comment]
.
